### ISSUE TITLE
No full proxy support

### ISSUE THREAD

**Issue by derhansen** [nitsan-technologies/ns_twitter#14]
When TYPO3 is configured to use a proxy server (`$GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy']['http']` and `$GLOBALS['TYPO3_CONF_VARS']['HTTP']['proxy']['https']`), the extension does not fully operate, since it uses a native PHP function to perform a HEAD request.

Affected code: https://github.com/nitsan-technologies/ns_twitter/blob/master/Classes/Controller/TweetController.php#L196

The `get_headers` request in line 196 of the TweetController executes a direct HEAD request to the Twitter API, which does not work, when the webserver / PHP is only able to perform requests through a proxy.

**Comment by nitsan-technologies** [comment]
Hey @derhansen 

Good catch!
Yes that was an issue.
We have fixed it in our latest release.
You can download it from (https://t3terminal.com/typo3-twitter-extension)
And soon will publish at TER with version 2.2.0

You may have a look at it and share your valuable feedback with us.

Cheers!
Team NITSAN

**Comment by derhansen** [comment]
The issue is still not fixed with the new version 2.2.0, since it still uses  `get_headers`

**Comment by derhansen** [comment]
The same applies to `file_get_contents` some lines after `get_headers`.

I suggest to use Guzzle instead, which respects all TYPO3 proxy settings. 

See example code here: https://github.com/derhansen/fe_change_pwd/commit/169a57779abbd959911ce7804b9001728ae78cdc

**Comment by nitsan-technologies** [comment]
Dear @derhansen 

We appreciate your feedback and accept our sincere apologies. Good news for you, we have released v2.2.1 with TYPO3 core's native HTTP PROXY support, Grab the latest version from https://extensions.typo3.org/extension/ns_twitter

Feel free to connect with us for any further request, feedback or suggestion to keep improve this extension, Thank you very much!

Cheers,
Team NITSAN
