### ISSUE TITLE
hide Answers from Twitter Feed

### ISSUE THREAD

**Issue by mightynico** [nitsan-technologies/ns_twitter#15]
It is possible to hide Answers wrote with our twitter Account at the nitsan timeline view? On Twitter there is a mode "only tweets" and "tweets and answers". We want to put only our tweets at our website and not the answers.
Thanks!

**Comment by nitsan-technologies** [comment]
Hey @mightynico 

We appreciate and thanks for your valuable feedback. Sounds a good idea to hide answers from the Twitter feed. We will do our best to work on this feature with the next release.

Cheers,
Sanjay

**Comment by nitsan-technologies** [comment]
Hey @matthewcooper 

We have adopted your suggestion and updated the extension.
You can download it from here (https://t3terminal.com/typo3-twitter-extension)
Soon will release at TER with version 2.2.0

You can have a look at it and any new suggestions are welcome.

Cheers
Team NITSAN!
