### ISSUE TITLE
no http proxy support

### ISSUE THREAD

**Issue by peterwimmer** [nitsan-technologies/ns_twitter#16]
like in ns_instagram there is no http proxy support. The call file_get_contents does not take the HTTP/proxy setting of typo3 in consideration. And there are two file_get_contents call in the code as far as i could see.

It seams that file_get_contents could be changed to respect a proxy: 

https://snippets.aktagon.com/snippets/371-how-to-use-file-get-contents-with-a-proxy

but the proxy definition seams a bit different (tcp://). I am not sure if this is the right approach to add proxy support, but at the moment it is definitly missing.

**Comment by nitsan-technologies** [comment]
Dear @peterwimmer  

We appreciate your feedback, Indeed Proxy-support is a bit important. Good news for you, we have released v2.2.1 with TYPO3 core's native HTTP PROXY support, Grab the latest version from https://extensions.typo3.org/extension/ns_twitter

Feel free to connect with us for any further request, feedback or suggestion to keep improve this extension, Thank you very much!

Cheers,
Team NITSAN
