### ISSUE TITLE
Unused code in controller

### ISSUE THREAD

**Issue by derhansen** [nitsan-technologies/ns_twitter#17]
In https://github.com/nitsan-technologies/ns_twitter/blob/master/Classes/Controller/TweetController.php, lines 64 - 66 are unused.

**Comment by nitsan-technologies** [comment]
Hello @derhansen 
Greetings of the day!

Firstly thank you very much for pointing out this. We really appreciate your contribution.

FYI, We have now removed that unused lines from the controller. You may now update the extension from the TER.

If you still find anything please don't hesitate to connect with us.

Regards!
NITSAN
