### ISSUE TITLE
Twitter account banned while using ns_twitter

### ISSUE THREAD

**Issue by csowebshk** [nitsan-technologies/ns_twitter#18]
Hey,
I'm using TYPO3 9.5.23 and ns_twitter 2.2.1.
Everything worked flawlessly until Twitter banned the account linked with the developer account without any reason. Didn't tweet anything and there were no violations against their TOS. Any informations on if this ever happened to someone? Tried contacting the twitter support but still waiting for an official answer.

Thanks in advance.

Chris

**Comment by nitsan-technologies** [comment]
Hello Chris
Greetings of the day!

Thank you for your message. There are more than 4000+ downloads up to now. But, no one reported such an issue in the past. For now, we are not sure about the suspension of your account. Please stay connected with Twitter support as per their guidelines. 

If you receive anything back from Twitter and if they suggest any issue with the extension, Then please inform us back here, It will be helpful to us to resolve the issue if there is any.

Wishing you a nice time ahead.

Thanks!
Team NITSAN

**Comment by csowebshk** [comment]
Thanks for the super quick response!

If I receive any infos from Twitter I will let you know!

Have a nice day.

Chris
