### ISSUE TITLE
Allow to enable/disable CSS

### ISSUE THREAD

**Issue by MySpace17** [nitsan-technologies/ns_twitter#2]
At the moment the exension loads the css files automaticly, sometimetimes at the end - Thats fatal if the website compress/concatenate the CSS.

Two solutions:
1. Set a class e.g. tx.nw_twitter  to let your css only works for your plugins
2. Let the user enable/disable your style-CSS and fontawesome-CSS e.g. by checkboxes.

**Comment by nitsan-technologies** [comment]
Hello @MySpace17 

Thanks for your great support.
We have adapted your changes and uploaded at TER with the new version of the extension.

 Thanks!
