### ISSUE TITLE
Plugin shows critical information frontend in case of an api error

### ISSUE THREAD

**Issue by peterwimmer** [nitsan-technologies/ns_twitter#20]
In case of an api error the plugin shows critical information like api keys in the frontend.

![image](https://user-images.githubusercontent.com/3355651/130249075-b09b6ee7-9d99-49d7-87c3-1952cfcc0437.png)

**Comment by nitsan-technologies** [comment]
Hello @peterwimmer
Greetings of the day!

Firstly thank you very much for pointing out the critical issue. We really appreciate your contribution.

FYI, We have now fixed this issue and taken care that the error should not show the important and critical information on the front. You may now update the extension from the TER.

If you still find anything please don't hesitate to connect with us.

Regards!
NITSAN
