### ISSUE TITLE
Array offset with curly braces deprecated (OAuthSignatureMethod)

### ISSUE THREAD

**Issue by clivebeckett** [nitsan-technologies/ns_twitter#22]
I got the following error message:

PHP Runtime Deprecation Notice: Array and string offset access syntax with curly braces is deprecated in /Classes/Contrib/OAuthSignatureMethod.php line 77

It was easy to fix, just replace the two sets of curly braces on line 77 with square brackets:

```php
$result |= ord($built{$i}) ^ ord($signature{$i});
```

has to be

```php
$result |= ord($built[$i]) ^ ord($signature[$i]);
```

**Comment by nitsan-technologies** [comment]
Hello @clivebeckett 
Greetings of the day!

We are very much thankful to you for your support and we really appreciate your contribution. I would just like to inform you that we have adopted this change and also released the new version.

Wishing you a great time.
Regards!
Team NITSAN
