### ISSUE TITLE
https twitter image

### ISSUE THREAD

**Issue by frodocat** [nitsan-technologies/ns_twitter#4]
In the template the url of the image "<img src="{orig_tweet.user.profile_image_url}" class="avatar" />" goes to http instead of https. In https I get an error that this is insecure.

**Comment by frodocat** [comment]
orig_tweet.user.profile_image_url

**Comment by nitsan-technologies** [comment]
Hello @frodocat 

Thank you very much for your time!

We have resolved this issue which you have mentioned here. Now profile image URL will set as **https://**.
You can get this latest updated extension from this repository (https://github.com/nitsan-technologies/ns_twitter).

We will update this in our next ns_twitter version for TER.

Cheers :)

**Comment by frodocat** [comment]
Thank you :-)
