### ISSUE TITLE
Error with hashtag containing accented characters

### ISSUE THREAD

**Issue by ziatl** [nitsan-technologies/ns_twitter#5]
I noticed an error that arises when a hash tag containing an accented character is recovered. The Hash tag is cut before the accented character which does not generate a link with all the hash tag.

Example: a hash tag [#santé] on twitter is generated [#sant]é in typo3.

Can you fix this bugs and update your super plugin!
Thank you for your plugin and your contributions!

**Comment by nitsan-technologies** [comment]
Hello @ziatl 

Thank you for your suggestion.

We have resolved it in our new version[2.0.0] of this extension. 
You can download it from here (https://extensions.typo3.org/extension/ns_twitter/) 

Have a great day ahead.

**Comment by nitsan-technologies** [comment]
> I noticed an error that arises when a hash tag containing an accented character is recovered. The Hash tag is cut before the accented character which does not generate a link with all the hash tag.
> 
> Example: a hash tag [#santé] on twitter is generated [#sant]é in typo3.
> 
> Can you fix this bugs and update your super plugin!
> Thank you for your plugin and your contributions!
