### ISSUE TITLE
Link twice

### ISSUE THREAD

**Issue by webcande** [nitsan-technologies/ns_twitter#8]
https://validator.w3.org shouted out, that "Start tag a seen but an element of the same type was already open."

Afterwards I saw in the code this:
`<p>Klinikum Frankfurt Höchst als Schwerpunktklinik für Herzinsuffizienz ausgezeichnet <a href="https://t.co/lh9wIhD10u" target="_blank"><a href="https://t.co/lh9wIhD10u" target="_blank">t.co/lh9wIhD10u</a></a></p>`

Developer tools changes the order, but still that is not correct:
![grafik](https://user-images.githubusercontent.com/17121088/62044577-9373da00-b203-11e9-8d79-fba41f16d18a.png)

This issue is existing in v 2 but v 2.0.2 has the same issue. With your template or mine. That makes no difference. 

PHP7.1, TYPO3 7ELTS. 

Did I miss something. Thanks in advance.

**Comment by nitsan-technologies** [comment]
Hey @webcande 

Thanks for using this extension.
Seems it's not an extension issue.
Looks like tweet there is link generated on the text and somehow you have removed the text and link remains the same. So will you please check that tweet?

Let me know if you found this extra link in every tweet.

Cheers! 
Team Nitsan
